# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: size_msg_bar.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import receiver.cclob_pb2 as cclob__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12size_msg_bar.proto\x12\x07message\x1a\x0b\x63\x63lob.proto\"\x84\x02\n\x0c\x43\x43\x42\x61rSizeMsg\x12\"\n\x06header\x18\x01 \x01(\x0b\x32\x12.message.MsgHeader\x12\x0c\n\x04\x66req\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\x12\x0c\n\x04open\x18\x04 \x01(\x01\x12\r\n\x05\x63lose\x18\x05 \x01(\x01\x12\x0c\n\x04high\x18\x06 \x01(\x01\x12\x0b\n\x03low\x18\x07 \x01(\x01\x12=\n\x1asize_bar_clusters_quantile\x18\x08 \x01(\x0b\x32\x19.message.CCSizeBarCluster\x12\x38\n\x15size_bar_clusters_std\x18\t \x01(\x0b\x32\x19.message.CCSizeBarCluster\"\x92\x04\n\x10\x43\x43SizeBarCluster\x12(\n\x0c\x42_small_size\x18\x01 \x01(\x0b\x32\x12.message.CCSizeBar\x12&\n\nB_mid_size\x18\x02 \x01(\x0b\x32\x12.message.CCSizeBar\x12(\n\x0c\x42_large_size\x18\x03 \x01(\x0b\x32\x12.message.CCSizeBar\x12*\n\x0e\x42_x_large_size\x18\x04 \x01(\x0b\x32\x12.message.CCSizeBar\x12(\n\x0cS_small_size\x18\x05 \x01(\x0b\x32\x12.message.CCSizeBar\x12&\n\nS_mid_size\x18\x06 \x01(\x0b\x32\x12.message.CCSizeBar\x12(\n\x0cS_large_size\x18\x07 \x01(\x0b\x32\x12.message.CCSizeBar\x12*\n\x0eS_x_large_size\x18\x08 \x01(\x0b\x32\x12.message.CCSizeBar\x12*\n\x0e\x61ll_small_size\x18\t \x01(\x0b\x32\x12.message.CCSizeBar\x12(\n\x0c\x61ll_mid_size\x18\n \x01(\x0b\x32\x12.message.CCSizeBar\x12*\n\x0e\x61ll_large_size\x18\x0b \x01(\x0b\x32\x12.message.CCSizeBar\x12,\n\x10\x61ll_x_large_size\x18\x0c \x01(\x0b\x32\x12.message.CCSizeBar\"?\n\tCCSizeBar\x12\x0e\n\x06volume\x18\x01 \x01(\x01\x12\x10\n\x08turnover\x18\x02 \x01(\x01\x12\x10\n\x08tradenum\x18\x03 \x01(\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'size_msg_bar_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CCBARSIZEMSG._serialized_start=45
  _CCBARSIZEMSG._serialized_end=305
  _CCSIZEBARCLUSTER._serialized_start=308
  _CCSIZEBARCLUSTER._serialized_end=838
  _CCSIZEBAR._serialized_start=840
  _CCSIZEBAR._serialized_end=903
# @@protoc_insertion_point(module_scope)
